### ISSUE TITLE
needs update

### ISSUE THREAD

**Issue by raivivek** [daler/hubward#2]
I recently found this repository and must say it is an incredibly useful package. Thanks for creating it. However, it looks like the recent `trackhub` versions have changed the API resulting in errors launching `hubward`.

Further, if you are busy and would like help, I'd be more than happy to resolve some issues.

```
Traceback (most recent call last):
  File "/home/vivekrai/.anaconda3/envs/py2/bin/hubward", line 12, in <module>
    import hubward
  File "/home/vivekrai/.anaconda3/envs/py2/lib/python2.7/site-packages/hubward/__init__.py", line 4, in <module>
    import models
  File "/home/vivekrai/.anaconda3/envs/py2/lib/python2.7/site-packages/hubward/models.py", line 11, in <module>
    from trackhub.upload import upload_hub, upload_track, upload_file
ImportError: cannot import name upload_track
```

**Comment by daler** [comment]
Thanks for using hubward, and thanks for reporting! I haven't been using this much recently but had made lots of changes to trackhub.

If you want to take a stab at fixing the easy issues that would be fantastic, I can clean up afterwards. Quite busy at the moment. Thanks!

**Comment by raivivek** [comment]
Okay, let me see. Will probably open more specific issues and resolve them incrementally. I appreciate your prompt response.

**Comment by raivivek** [comment]
Hi @daler ; Could you clarify a few things?

If I have already processed my files and want to specify them directly, what do I do? From what little tinkering I did, it seemed to require all field (`script`, `processed`, `source` etc) even if I don't need any of it.

**Comment by daler** [comment]
@raivivek the original intent was only for publicly accessible data. Unfortunately I don't think there's good support for local pre-processed data. For existing data you might want to just use [trackhub](https://github.com/daler/trackhub) directly.

Alternatively you might be able to fool it with symlinks, a file:// URI as the source, and the processing "script" just performs a symlink.

**Comment by raivivek** [comment]
Thanks! I suppose writing a wrapper around trackhub will be a better option
